name       : flask-cors
version    : 3.0.8
release    : 1
source     :
    - https://github.com/corydolphin/flask-cors/archive/3.0.8.tar.gz : 11613661a7d711dd1abc5159a9811fb64f72424b2506d139fc064f37a8e1c2ba
license    : MIT
component  : programming-python
summary    : Cross Origin Resource Sharing ( CORS ) support for Flask
description: |
    A Flask extension for handling Cross Origin Resource Sharing (CORS), making cross-origin AJAX possible.
builddeps  :
    - flask
rundeps    :
    - flask
build      : |
    %python3_setup
install    : |
    %python3_install
