name       : flask-cors
version    : 3.0.9
release    : 2
source     :
    - https://github.com/corydolphin/flask-cors/archive/3.0.9.tar.gz : d1d40cfd97f7b126db99ae82df20a8748124d1cd7467b463217e9e043db43658
license    : MIT
component  : programming-python
summary    : Cross Origin Resource Sharing ( CORS ) support for Flask
description: |
    A Flask extension for handling Cross Origin Resource Sharing (CORS), making cross-origin AJAX possible.
builddeps  :
    - flask
    - python-nose
    - python-packaging
rundeps    :
    - flask
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
