name       : flask-cors
version    : 3.1.01
release    : 7
source     :
    - https://github.com/corydolphin/flask-cors/archive/refs/tags/3.1.01.tar.gz : bd5b6b31f4e0b2f698c790743b1db5553d447df2144ef0555e28914756d32c98
license    : MIT
component  : programming.python
summary    : Cross Origin Resource Sharing ( CORS ) support for Flask
description: |
    A Flask extension for handling Cross Origin Resource Sharing (CORS), making cross-origin AJAX possible.
builddeps  :
    - flask
    - python-nose
    - python-packaging
rundeps    :
    - flask
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
